# Generated by Django 5.1.7 on 2025-04-21 12:51

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='book.cart', verbose_name='Savat'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='book.category', verbose_name='Ota-ona'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitob_comments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='kitob',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitoblar', to='book.category', verbose_name='Kategorya'),
        ),
        migrations.AddField(
            model_name='comment',
            name='kitob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.kitob', verbose_name='Kitob'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='kitob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.kitob', verbose_name='Kitob'),
        ),
        migrations.AddField(
            model_name='like',
            name='kitob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='book.kitob', verbose_name='Kitob'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitob_likes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='book_catego_slug_8bf602_idx'),
        ),
        migrations.AddIndex(
            model_name='kitob',
            index=models.Index(fields=['name', 'author'], name='book_kitob_name_3922ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kitob',
            unique_together={('name', 'author', 'publication_year')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['kitob', 'created_at'], name='book_commen_kitob_i_b898ba_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'kitob'], name='book_cartit_cart_id_1c9db9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'kitob')},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'kitob'], name='book_like_user_id_a8e5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['created_at'], name='book_like_created_6e7148_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'kitob')},
        ),
    ]
