# Generated by Django 5.1.7 on 2025-06-05 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costom_user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami to'g'ri formatda kiritilishi kerak. Masalan, +998901234567", regex='^\\+?\\d{1,3}[-.\\s]?\\d{3,4}[-.\\s]?\\d{4,8}$')], verbose_name='Telefon'),
        ),
    ]
